### ISSUE TITLE
Closes the Game instead of the obsolete tslgame.exe

### ISSUE THREAD

**Issue by darkerazor** [romestylez/fix-pubg#1]
Hi
As the title says, I wanted to try out this script.
Problem is, it just closes my game after 120 seconds, instead of stopping the unwanted tsp game.exe
What can be done?
Do you require more information?
Thanks

**Comment by romestylez** [comment]
Hi,
thanks for the feedback. For me and a friend it was running fine. I have changed something can you maybe download and try again ?

**Comment by darkerazor** [comment]
Hi again,
downloaded the new version, same issue as before. After starting the game via your script, I was in the lobby. After the 120 seconds, the game got closed.

**Comment by romestylez** [comment]
Very wired... I had no trouble until my game crashed... After that i had the same problem like you. I have changed the code can you please try it again :)

**Comment by darkerazor** [comment]
Hi
Now the game does not even start. Steam gives back an error message upon
start.

romestylez ***@***.***> schrieb am Mo., 29. Jan. 2024, 17:46:

**Comment by romestylez** [comment]
Ive updated the code again. For me and all my friends this is working just fine. Yesterday there way an update and a Steam Popup windows after starting the game. Thats no error.

If you get an error please add a screenshot.

**Comment by darkerazor** [comment]
Hi,

Now it seems to be working. Game stays running.
Thanks again

Am Mi., 31. Jan. 2024 um 10:10 Uhr schrieb romestylez <
***@***.***>:

**Comment by romestylez** [comment]
Perfect mate. No problem :)
